---
Name: lifeboat_silverstripe_app
---
SilverStripe\View\SSViewer:
  rewrite_hash_links: false

SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

SilverStripe\Control\Session:
  cookie_secure: true

Lifeboat\Models\Site:
  APP_ID: '`LIFEBOAT_APP_ID`'
  APP_SECRET: '`LIFEBOAT_APP_SECRET`'